=== pnordhus/openorbiter/data/maps/oomap.dtd
<!ELEMENT oomap			(spawn,spawn,spawn,spawn,spawn,spawn,spawn,spawn,spawn*,node+,bouncer*)>
<!ELEMENT spawn			(#PCDATA)>
<!ELEMENT node			(#PCDATA)>
<!ELEMENT bouncer		(#PCDATA)>

<!ATTLIST map	name			CDATA	#REQUIRED>
<!ATTLIST map	width			CDATA	#REQUIRED>
<!ATTLIST map	height			CDATA	#REQUIRED>
<!ATTLIST map	gravityX		CDATA	"0.0">
<!ATTLIST map	gravityY		CDATA	"10.0">

<!ATTLIST spawn	x				CDATA	#REQUIRED>
<!ATTLIST spawn	y				CDATA	#REQUIRED>

<!ATTLIST node	x				CDATA	#REQUIRED>
<!ATTLIST node	y				CDATA	#REQUIRED>

<!ATTLIST bouncer	x1			CDATA	#REQUIRED>
<!ATTLIST bouncer	y1			CDATA	#REQUIRED>
<!ATTLIST bouncer	x2			CDATA	#REQUIRED>
<!ATTLIST bouncer	y2			CDATA	#REQUIRED>
<!ATTLIST bouncer	width		CDATA	#REQUIRED>
<!ATTLIST bouncer	boost		CDATA	"0.0">
<!ATTLIST bouncer	boostScale	CDATA	"1.0">
<!ATTLIST bouncer	unlink		CDATA	"true">

=== pnordhus/openorbiter/data/maps/double.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="Double" width="50" height="37.5">
	<author>Philipp Nordhus</author>
	<name lang="de">Doppelt h√§lt besser</name>
	
	<spawn x="13.75" y="2.5" />
	<spawn x="21.25" y="2.5" />
	<spawn x="28.75" y="2.5" />
	<spawn x="36.25" y="2.5" />
	
	<spawn x="10" y="7.5" />
	<spawn x="17.5" y="7.5" />
	<spawn x="32.5" y="7.5" />
	<spawn x="40" y="7.5" />
	
	<node x="18.75" y="12.5" />
	<node x="31.25" y="25" />
</oomap>

=== pnordhus/openorbiter/data/maps/diagonalis.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="Diagonalis" width="40" height="40" difficulty="easy">
	<author>Bernd HÃ¼gel</author>
	
	<spawn x="10" y="2" />
	<spawn x="15" y="2" />
	<spawn x="25" y="2" />
	<spawn x="30" y="2" />
	
	<spawn x="12.5" y="4" />
	<spawn x="17.5" y="4" />
	<spawn x="22.5" y="4" />
	<spawn x="27.5" y="4" />
	
	<node x="20" y="20" />
	
	<bouncer x1="0" y1="0" x2="20" y2="0" width="0.5" boost="3" />
	<bouncer x1="0" y1="0" x2="0" y2="20" width="0.5" boost="3" />
	
	<bouncer x1="40" y1="40" x2="20" y2="40" width="0.5" boost="3" />
	<bouncer x1="40" y1="40" x2="40" y2="20" width="0.5" boost="3" />
</oomap>

=== pnordhus/openorbiter/data/maps/deadpoint.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="Left Dead-point" width="60" height="40" difficulty="normal">
	<author>Bernd HÃ¼gel</author>
	<name lang="de">Todespunkt: Links</name>
	
	<spawn x="10" y="2" />
	<spawn x="15" y="2" />
	<spawn x="25" y="2" />
	<spawn x="30" y="2" />
	
	<spawn x="12.5" y="4" />
	<spawn x="17.5" y="4" />
	<spawn x="22.5" y="4" />
	<spawn x="27.5" y="4" />
	
	<node x="5" y="20" />
	<node x="40" y="20" />
	
	<bouncer x1="0" y1="0" x2="0" y2="40" width="0.5" boost="5" unlink="false" />
	<bouncer x1="20" y1="40" x2="40" y2="40" width="0.5" boost="3" />
	<bouncer x1="50" y1="40" x2="60" y2="40" width="0.5" boost="3" />
	<bouncer x1="60" y1="30" x2="60" y2="40" width="0.5" boost="3" />
</oomap>

=== pnordhus/openorbiter/data/maps/triangle.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="Bermuda Triangle" width="40" height="30">
	<spawn x="10" y="2" />
	<spawn x="15" y="2" />
	<spawn x="25" y="2" />
	<spawn x="30" y="2" />
	
	<spawn x="12.5" y="4" />
	<spawn x="17.5" y="4" />
	<spawn x="22.5" y="4" />
	<spawn x="27.5" y="4" />
	
	<node x="20" y="10" />
	<node x="14.33" y="20" />
	<node x="25.77" y="20" />
</oomap>
