=== pnordhus/openorbiter/data/maps/oomap.dtd
<!ELEMENT oomap			(spawn,spawn,spawn,spawn,spawn,spawn,spawn,spawn,spawn*,node+,bouncer*)>
<!ELEMENT spawn			(#PCDATA)>
<!ELEMENT node			(#PCDATA)>
<!ELEMENT bouncer		(#PCDATA)>

<!ATTLIST map	name			CDATA	#REQUIRED>
<!ATTLIST map	width			CDATA	#REQUIRED>
<!ATTLIST map	height			CDATA	#REQUIRED>
<!ATTLIST map	gravityX		CDATA	"0.0">
<!ATTLIST map	gravityY		CDATA	"10.0">

<!ATTLIST spawn	x				CDATA	#REQUIRED>
<!ATTLIST spawn	y				CDATA	#REQUIRED>

<!ATTLIST node	x				CDATA	#REQUIRED>
<!ATTLIST node	y				CDATA	#REQUIRED>

<!ATTLIST bouncer	x1			CDATA	#REQUIRED>
<!ATTLIST bouncer	y1			CDATA	#REQUIRED>
<!ATTLIST bouncer	x2			CDATA	#REQUIRED>
<!ATTLIST bouncer	y2			CDATA	#REQUIRED>
<!ATTLIST bouncer	width		CDATA	#REQUIRED>
<!ATTLIST bouncer	boost		CDATA	"0.0">
<!ATTLIST bouncer	boostScale	CDATA	"1.0">
<!ATTLIST bouncer	unlink		CDATA	"true">

=== pnordhus/openorbiter/data/maps/dropout.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="Right Drop-out" width="40" height="40" difficulty="hard">
	<author>Bernd HÃ¼gel</author>
	<name lang="de">Sie fallen nach rechts</name>
	
	<spawn x="10" y="2" />
	<spawn x="15" y="2" />
	<spawn x="25" y="2" />
	<spawn x="30" y="2" />
	
	<spawn x="12.5" y="4" />
	<spawn x="17.5" y="4" />
	<spawn x="22.5" y="4" />
	<spawn x="27.5" y="4" />
	
	<node x="10" y="10" />
	<node x="20" y="20" />
	<node x="30" y="30" />
	
	<node x="20" y="10" />
	<node x="30" y="20" />
	
	<bouncer x1="0" y1="0" x2="10" y2="0" width="0.5" boost="1" unlink="false" />
	<bouncer x1="0" y1="0" x2="0" y2="40" width="0.5" boost="1" unlink="false" />
	<bouncer x1="10" y1="40" x2="30" y2="40" width="0.5" boost="1" unlink="false" />
	
	<bouncer x1="10" y1="10" x2="20" y2="10" width="0.5" boost="1" unlink="false" />
	<bouncer x1="20" y1="20" x2="30" y2="20" width="0.5" boost="1" unlink="false" />
	<bouncer x1="30" y1="30" x2="40" y2="30" width="0.5" boost="1" unlink="false" />
</oomap>

=== pnordhus/openorbiter/data/maps/eight.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="Magic 8-Room" width="40" height="60">
	<spawn x="18.5" y="3" />
	<spawn x="21.5" y="3" />
	
	<spawn x="15.5" y="6" />
	<spawn x="24.5" y="6" />
	
	<spawn x="12.5" y="9" />
	<spawn x="27.5" y="9" />
	
	<spawn x="9.5" y="12" />
	<spawn x="30.5" y="12" />
	
	<node x="20" y="15" />
	<node x="20" y="45" />
	
	<bouncer x1="15" y1="0" x2="0" y2="15" width="0.5" boost="3" />
	<bouncer x1="0" y1="15" x2="15" y2="30" width="0.5" boost="3" />
	<bouncer x1="15" y1="30" x2="0" y2="45" width="0.5" boost="3" />
	<bouncer x1="0" y1="45" x2="15" y2="60" width="0.5" boost="3" />
	
	<bouncer x1="25" y1="0" x2="40" y2="15" width="0.5" boost="3" />
	<bouncer x1="40" y1="15" x2="25" y2="30" width="0.5" boost="3" />
	<bouncer x1="25" y1="30" x2="40" y2="45" width="0.5" boost="3" />
	<bouncer x1="40" y1="45" x2="25" y2="60" width="0.5" boost="3" />
</oomap>

=== pnordhus/openorbiter/data/maps/cage.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="The Cage" width="40" height="30.0" gravityX="0" gravityY="9.375">
	<author>OpenOrbiter Testing Squad</author>

	<spawn x="10" y="2" />
	<spawn x="15" y="2" />
	<spawn x="25" y="2" />
	<spawn x="30" y="2" />

	<spawn x="12.5" y="4" />
	<spawn x="17.5" y="4" />
	<spawn x="22.5" y="4" />
	<spawn x="27.5" y="4" />

	<node x="20" y="15" />

	<bouncer x1="10" y1="0" x2="30" y2="0" width="0.5" boost="2" />
	<bouncer x1="10" y1="30" x2="30" y2="30" width="0.5" boost="2" />
	
	<bouncer x1="0" y1="10" x2="0" y2="20" width="0.5" boost="2" />
	<bouncer x1="40" y1="10" x2="40" y2="20" width="0.5" boost="2" />
</oomap>

=== pnordhus/openorbiter/data/maps/single.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="One node to rule them all" width="40" height="30" difficulty="normal">
	<author>Philipp Nordhus</author>
	<name lang="de">Ein Knoten, sie zu knechten</name>
	
	<spawn x="10" y="2" />
	<spawn x="15" y="2" />
	<spawn x="25" y="2" />
	<spawn x="30" y="2" />
	
	<spawn x="12.5" y="4" />
	<spawn x="17.5" y="4" />
	<spawn x="22.5" y="4" />
	<spawn x="27.5" y="4" />
	
	<node x="20" y="15" />
</oomap>

=== pnordhus/openorbiter/data/maps/hourglass.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="Broken Hourglass" width="30" height="40" difficulty="hard">
	<author>Bernd HÃ¼gel</author>
	<name lang="de">Kaputte Sanduhr</name>
	
	<spawn x="5" y="2" />
	<spawn x="10" y="2" />
	<spawn x="20" y="2" />
	<spawn x="25" y="2" />
	
	<spawn x="7.5" y="4" />
	<spawn x="12.5" y="4" />
	<spawn x="17.5" y="4" />
	<spawn x="22.5" y="4" />
	
	<node x="15" y="10" />
	
	<bouncer x1="0" y1="0" x2="30" y2="0" width="0.5" boost="3" />
	<bouncer x1="0" y1="40" x2="30" y2="40" width="0.5" boost="3" />
	
	<bouncer x1="0" y1="0" x2="0" y2="15" width="0.5" boost="3" />
	<bouncer x1="0" y1="15" x2="10" y2="25" width="0.5" boost="3" />
	
	<bouncer x1="30" y1="0" x2="30" y2="15" width="0.5" boost="3" />
	<bouncer x1="30" y1="15" x2="20" y2="25" width="0.5" boost="3" />
	
	<bouncer x1="0" y1="40" x2="0" y2="25" width="0.5" boost="3" />
	<bouncer x1="30" y1="40" x2="30" y2="25" width="0.5" boost="3" />
</oomap>

=== pnordhus/openorbiter/data/maps/bar.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="SCUMM Bar" width="60" height="40">
	<spawn x="13.75" y="2.5" />
	<spawn x="21.25" y="2.5" />
	<spawn x="28.75" y="2.5" />
	<spawn x="36.25" y="2.5" />
	
	<spawn x="10" y="7.5" />
	<spawn x="17.5" y="7.5" />
	<spawn x="32.5" y="7.5" />
	<spawn x="40" y="7.5" />
	
	<node x="20" y="20" />
	<node x="40" y="20" />
	
	<bouncer x1="25" y1="20" x2="35" y2="20" width="0.5" boost="2" />
</oomap>

=== pnordhus/openorbiter/data/maps/dipper.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="The Big Dipper" width="50" height="37.5" gravityX="0" gravityY="9.375">
	<author>OpenOrbiter Testing Squad</author>

	<spawn x="13.75" y="2.5" />
	<spawn x="21.25" y="2.5" />
	<spawn x="28.75" y="2.5" />
	<spawn x="36.25" y="2.5" />

	<spawn x="10" y="7.5" />
	<spawn x="17.5" y="7.5" />
	<spawn x="32.5" y="7.5" />
	<spawn x="40" y="7.5" />

	<node x="18.75" y="12.5" />
	<node x="31.25" y="25" />

	<bouncer x1="0" y1="37.5" x2="50" y2="37.5" width="0.5" boost="2" />
	<bouncer x1="0" y1="0" x2="0" y2="37.5" width="0.5" boost="2" />
	<bouncer x1="50" y1="0" x2="50" y2="37.5" width="0.5" boost="2" />
</oomap>

=== pnordhus/openorbiter/data/maps/4traps.xml
<?xml version="1.0"?>
<!DOCTYPE oomap SYSTEM "oomap.dtd">

<oomap name="Four Traps" width="40" height="40">
	<author>Bernd HÃ¼gel</author>
	<name lang="de">Vier Fallen</name>
	
	<spawn x="10" y="2" />
	<spawn x="15" y="2" />
	<spawn x="25" y="2" />
	<spawn x="30" y="2" />
	
	<spawn x="12.5" y="4" />
	<spawn x="17.5" y="4" />
	<spawn x="22.5" y="4" />
	<spawn x="27.5" y="4" />
	
	<node x="20" y="20" />
	
	<bouncer x1="10" y1="0" x2="30" y2="0" width="0.5" boost="1" unlink="false" />
	<bouncer x1="10" y1="0" x2="15" y2="5" width="0.5" boost="1" unlink="false" />
	<bouncer x1="30" y1="0" x2="25" y2="5" width="0.5" boost="1" unlink="false" />
	
	<bouncer x1="10" y1="40" x2="30" y2="40" width="0.5" boost="1" unlink="false" />
	<bouncer x1="10" y1="40" x2="15" y2="35" width="0.5" boost="1" unlink="false" />
	<bouncer x1="30" y1="40" x2="25" y2="35" width="0.5" boost="1" unlink="false" />
	
	<bouncer x1="0" y1="10" x2="0" y2="30" width="0.5" boost="1" unlink="false" />
	<bouncer x1="0" y1="10" x2="5" y2="15" width="0.5" boost="1" unlink="false" />
	<bouncer x1="0" y1="30" x2="5" y2="25" width="0.5" boost="1" unlink="false" />
	
	<bouncer x1="40" y1="10" x2="40" y2="30" width="0.5" boost="1" unlink="false" />
	<bouncer x1="40" y1="10" x2="35" y2="15" width="0.5" boost="1" unlink="false" />
	<bouncer x1="40" y1="30" x2="35" y2="25" width="0.5" boost="1" unlink="false" />
</oomap>
